### ISSUE TITLE
NuxtJS Route Changing Issue

### ISSUE THREAD

**Issue by BerkanSezer** [avil13/vue-sweetalert2#101]
## NuxtJS Route Changing Issue
Hi, I found a bug. Scenario is like that:
- Show any sweetAlert
- Click a nuxt-link for go to another page before the toast alert close.
- New page will render with shadow. Because sweetAlert didn't end.
- And it shows this error: ```Uncaught TypeError: Cannot read property 'removeEventListener' of undefined```

**Comment by avil13** [comment]
Hi.

I suggest using a hook for forced closure. In `beforeRouteUpdate` for example .

Adding such functionality to the library looks redundant.
