### ISSUE TITLE
Could not find a declaration file for module 'sweetalert2/dist/sweetalert2.js'

### ISSUE THREAD

**Issue by masashi-sutou** [avil13/vue-sweetalert2#102]
## what's the problem

- run `cross-env NODE_ENV=development nuxt-ts`, I get the following error.

```node
2:41 Could not find a declaration file for module 'sweetalert2/dist/sweetalert2.js'. '~/my_project_name/app/node_modules/sweetalert2/dist/sweetalert2.js' implicitly has an 'any' type.
  Try `npm install @types/sweetalert2` if it exists or add a new declaration (.d.ts) file containing `declare module 'sweetalert2/dist/sweetalert2.js';`
    1 | import Vue from 'vue';
  > 2 | import Swal, { SweetAlertOptions } from 'sweetalert2/dist/sweetalert2.js';
      |                                         ^
    3 | declare type VueSwalInstance = typeof Swal.fire;
    4 | declare module 'vue/types/vue' {
    5 |     interface Vue {
```

- I read README.md and edited nuxt.config.js and tsconfig.json.

```js
//  nuxt.config.js

  modules: [
    'vue-sweetalert2/nuxt',
  ],
```

```json
//  tsconfig.json

  "types": [
    "vue-sweetalert2"
  ],
```

- related issue: https://github.com/avil13/vue-sweetalert2/issues/61

## environment

  - Version: "vue-sweetalert2": "3.0.5"
  - Platform: "nuxt": "2.12.2",
    - "@nuxt/typescript-runtime": "0.4.8"
    - "@nuxt/typescript-build": "1.0.1"

## workaround

- I downgrade vue-sweetalert2:v2.1.1.

**Comment by grippado** [comment]
downgrade to v2.1.1 its the only way to solve type problem on nuxt build, in my case!

**Comment by avil13** [comment]
Hi.
Try this 
```ts
 import Swal from 'sweetalert2/dist/sweetalert2.js';
 import { SweetAlertOptions } from 'sweetalert2'; //  This is Interface. js files don't store interfaces
```

**Comment by grippado** [comment]
> Hi.
> Try this
> 
> ```ts
>  import Swal from 'sweetalert2/dist/sweetalert2.js';
>  import { SweetAlertOptions } from 'sweetalert2'; //  This is Interface. js files don't store interfaces
> ```

@avil13 This solution would be within the specific component, where do you want to use SweetAlert2?

**Comment by avil13** [comment]
@grippado Excuse me. Hurried up with the answer.

This bug came out of this commit.  (https://github.com/avil13/vue-sweetalert2/commit/a2f172880338a002e289f7a9b9266932166948ad), I'll try to fix it now.

**Comment by avil13** [comment]
@masashi-sutou fixed in v3.0.6

**Comment by grippado** [comment]
@avil13 in nuxt, I'm force import css in `nuxt.config`, this commit resolve this too?
```
css: [
     'sweetalert2/dist/sweetalert2.css'
],
```
thx for quick response and interaction <3

**Comment by avil13** [comment]
@grippado  I will try to install a fresh Nuxt and play it.

**Comment by grippado** [comment]
> @grippado I will try to install a fresh Nuxt and play it.

@avil13 at v3.0.6, and Nuxt v2.13.11, Ill removed import CSS from `nuxt.config`, and it is fully useful and functionally
![image](https://user-images.githubusercontent.com/550632/86021879-febfc080-b9ff-11ea-9f0b-02b736d05c3b.png)

**Comment by avil13** [comment]
@grippado Actually, it's a problem because there was a issue of how to customize alert themes.
And that's exactly what you can do by connecting the styles separately.

I will leave this functionality in this version, but I will have to think about how to solve it better.
Thank you for your feedback.
