### ISSUE TITLE
Nuxt - No CSS

### ISSUE THREAD

**Issue by Aontaigh** [avil13/vue-sweetalert2#103]
- Version: ^3.0.5
  - Platform: MacOS
  - Subsystem: Nuxt ^2.12.2

As you can see from this screenshot (Link: https://i.imgur.com/WIfyEVf.png), the styling is missing from the sweetalert dialog. Within the nodemodules folder, upon navigating to vue-sweetalert2, there is no .css files contained in any folder.

**Comment by Aontaigh** [comment]
In my nuxt.config.js the following was added to the CSS array which fixed the issue:

`css: ['sweetalert2/dist/sweetalert2.min.css']`

**Comment by jonalxh** [comment]
Thanks @Aontaigh it helped me a lot.
