### ISSUE TITLE
SCSS not getting packed with webpack

### ISSUE THREAD

**Issue by pistol-whip** [avil13/vue-sweetalert2#106]
vue-sweetalert has been added via `yarn add vue-sweetalert2` and successfully installed.

```js
// main.js
import Vue from 'vue';
import VueSweetalert2 from 'vue-sweetalert2';

import "@/design/index.scss";

Vue.use(VueSweetalert2);
```

```scss
// index.scss
@import '~sweetalert2/src/variables';
$swal2-background: #2A3042;
@import '~sweetalert2/src/sweetalert2';
```

This is not getting compiled and resulting calls for an alert result in a white background.

**Comment by avil13** [comment]
Hi. 
Not sure I understand the question, but this example will not help?

https://github.com/avil13/vue-sweetalert2-example/blob/3f312e3ea0c0b6536ae7e01139b7555ddbb78810/src/components/BlackAlert.vue#L95
