### ISSUE TITLE
vue js elements within the html option

### ISSUE THREAD

**Issue by nunob87** [avil13/vue-sweetalert2#107]
hello,

this.$swal({...,  html: ....here...

of "html" not to use vue js components, elements??

thanks

**Comment by avil13** [comment]
Hi.
No, I was not able to solve the problem with the compilation of the template in this scope.

**Comment by nunob87** [comment]
don't you know any trick, in which you can use sweetalert, without needing to change for modals?

**Comment by avil13** [comment]
Can in more detail describe the situation? 
And better with code example

**Comment by nunob87** [comment]
I need to use vue2-datepicker, within several forms, which are already created, since the rest of the application is what to use to select dates.

**Comment by avil13** [comment]
I'm sorry, but as datepicker is a component separated of Vue, I don't know what to help you.
If you use Vuetify there are ready-made solutions.

**Comment by nunob87** [comment]
I don't use, I will make the forms in modal

thanks
