### ISSUE TITLE
this.$swal.close() isn't working on v.3.0.3

### ISSUE THREAD

**Issue by ffmatheus** [avil13/vue-sweetalert2#109]
When i tried to close a window to open another with a error message using this.$swal.close(), the function is not recognized.
I'm using a multiple inputs example.

**Comment by avil13** [comment]
Good afternoon. Can I see a full code sample?
It looks like an error not in the library.

**Comment by RexHung0302** [comment]
hi i can't use too,
did it fixed?

my code :

```
this.$swal({
          title: 'Wait plz!',
          allowOutsideClick: false,
          onBeforeOpen: () => {
            Swal.showLoading();
   }
 });


setTimeout(() => {
     console.log(this.$swal.close());
    vm.nowStep = 3;
}, 2000);
```

**Comment by ffmatheus** [comment]
It doesn't , i need to use another package with CDN.

**Comment by avil13** [comment]
@RexHung0302 

```ts

const item = this.$swal({
          title: 'Wait plz!',
          allowOutsideClick: false,
          onBeforeOpen: () => {
            Swal.showLoading();
   }
 });


setTimeout(() => {
    item.close();
}, 2000);


```

**Comment by avil13** [comment]
@RexHung0302 

```ts
const item =this.$swal({
          title: 'Wait plz!',
          allowOutsideClick: false,
          onBeforeOpen: () => {
            Swal.showLoading();
   }
 });


setTimeout(() => {
    item.close();
}, 2000);
```

https://sweetalert2.github.io/#methods

> Close the currently open SweetAlert2 modal programmatically, the Promise returned by Swal.fire() will be resolved with an empty object { }
