### ISSUE TITLE
What's difference between your Vue-component and lishengzxc/vue-sweetalert?

### ISSUE THREAD

**Issue by koddr** [avil13/vue-sweetalert2#11]
Hello.

Can you tell me please, what's principal difference between your Vue-component and [lishengzxc/vue-sweetalert](https://github.com/lishengzxc/vue-sweetalert)? Maybe size or other useful feature?

I found your component in [this article](https://alligator.io/vuejs/vue-sweetalert2/), btw. 

Would be great for understand it and finally use one 👍

**Comment by avil13** [comment]
Hello.

If you look at the source, then there is not much difference. 
Simply, this plugin is written according to the recommendations of vuejs.

Plus, talked a little with the authors of SweatAlert2 on how best to organize support.

In any case, choose you.

I wish you success in its use.

**Comment by koddr** [comment]
@avil13 oh, I see 👍 

Simple little question about working with component here... So, can I place something to component (as slot) and get this data on parent component? 

For more understanding: I've form on site and after save it, I want to check if user is `logged in` to site (Django as backend). If `logged in` — success form and show success SA2 alert. If `not logged in` — show in SA2 alert two fields (email and password) and `Login` button. Finally, user enter right email and password and form is success.

**Comment by avil13** [comment]
Forgive me for a long time I could not answer.

The variables in the component have scope only in the component.
To transfer this data, you can use callbacks passing methods or using events via $emit.

Personally, I would prefer to use Vuex for all this.

I hope that I correctly understood the question and was able to give a suitable answer.
