### ISSUE TITLE
Import vue-sweetalert2 in SSR environment: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by phlegx** [avil13/vue-sweetalert2#111]
Hi!

If I use vue-sweetalert2 with an SSR environment, I get this error:

```
node_modules/vue-sweetalert2/dist/index.js:8
    import Swal from 'sweetalert2';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

Any idea how to solve this problem?

**Version:** 3.0.8
**Vue:** 2.6.12

**Comment by avil13** [comment]
Hi!
Are you using nuxt?

**Comment by phlegx** [comment]
No, I use UVue: https://universal-vue.github.io/docs/

**Comment by avil13** [comment]
Thank you, I'll need to study the documentation and make corrections.

**Comment by phlegx** [comment]
I'm not sure, but could this be a solution? https://universal-vue.github.io/docs/guide/usage.html#use-ssr-non-compatible-libraries

**Comment by avil13** [comment]
Is your project closed? 
Deploying a new project on a machine is expensive, so I could test everything on an example.

**Comment by phlegx** [comment]
It is closed. I have tried to add this config to my `uvue.config.js`, that imports vue-sweetalert2 only on spa.

```js
export default {
  plugins: [...],
  imports: [
    {
      src: '@/alerts',
      ssr: false,
    },
    {
      src: 'sweetalert2/dist/sweetalert2.min.css',
      ssr: false,
    },
  ],
}
```

And the js file:

```js
import Vue from 'vue'
import VueSweetalert2 from 'vue-sweetalert2'

Vue.use(VueSweetalert2)
```

**Comment by phlegx** [comment]
@avil13 see this example app here: https://github.com/universal-vue/examples

**Comment by phlegx** [comment]
**SOLVED WITH**

```js
/* vue.config.js */

module.exports = {
  transpileDependencies: [/vue-sweetalert2/]
}
```

Many thx to @chymz from Uvue!
