### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by narenderv7** [avil13/vue-sweetalert2#115]
Would be nice to support Vue 3 😃

**Comment by avil13** [comment]
If you use the Composition API. Outside of the "setup" function, everything remains as it was.

**Comment by narenderv7** [comment]
you can use Composition API with Vue@2 but If you directly using Vue@3, this library won't support as `prototype is not available in Vue@3`. We will end up getting this error `Uncaught TypeError: vue.prototype is undefined`.

**Comment by avil13** [comment]
Fixed in version `4.0.1` https://github.com/avil13/vue-sweetalert2#vue-3
