### ISSUE TITLE
Prevent auto import of sweetalert style

### ISSUE THREAD

**Issue by AleeeKoi** [avil13/vue-sweetalert2#116]
Hello, 
in the current version 4.0.1 the default style of sweetalert2 is automatically included. 
I see old PRs where this behavior was fixed.
Please, could you permit to not include automatically the style?
Thank you

**Comment by AleeeKoi** [comment]
Hi @avil13 , will it be fixed? Thank you

**Comment by avil13** [comment]
Hi @AleeeKoi . Yes. I downloaded the library wrong before. Now it is fixed.
