### ISSUE TITLE
CSS is automatically added to inline style.

### ISSUE THREAD

**Issue by Stehos** [avil13/vue-sweetalert2#118]
Hello, 
is there any real way how can I remove all inline styles and include style manually only if I want?

```
import VueSweetalert2 from 'vue-sweetalert2';
Vue.use(VueSweetalert2);
```
Includes also default styling. I tried to update the file above to prevent loading styles but without any effect. Please what exactly is needed to remove? I am asking based on the description:
```

// If you don't need the styles, do not connect
import 'sweetalert2/dist/sweetalert2.min.css';
```

Thank you.

**Comment by avil13** [comment]
Hi.
What version do you use?

**Comment by Stehos** [comment]
Hi @avil13 , Vue is 2.6.12

and lib:

"vue-sweetalert2": "^4.1.1",

**Comment by avil13** [comment]
I tried to do it again in an example of this package, and everything worked as expected.
If you comment on the styles, they do not connect.

https://github.com/avil13/vue-sweetalert2/blob/5aa08de7ef7a55e59d8ab0b2c0d1d762fbcc83e5/packages/example/src/main.js#L8

![image](https://user-images.githubusercontent.com/1606172/98536994-ad6eea00-2299-11eb-9b76-28320835c149.png)

**Comment by avil13** [comment]
@Stehos  Check if `sweetalert2 ` is connected separately.

**Comment by Stehos** [comment]
@avil13  thank you for your reply. I have it done in the same way as you mentioned:

```
import VueSweetalert2 from 'vue-sweetalert2';
//import 'sweetalert2/dist/sweetalert2.min.css';
Vue.use(VueSweetalert2);
```

and it does not matter if i comment or uncomment import 'sweetalert2/dist/sweetalert2.min.css'; The style is inserted in the header inline style tag every time. I also checked, if there are no other css imports and nothing else is included - just sweetalert styles starting by:

`<style>.swal2-popup.swal2-toast{flex-direction:row;align-items:cen`

Thank you.

**Comment by avil13** [comment]
@Stehos is your repository private? Maybe if I could look at it, something would tell me.

**Comment by Stehos** [comment]
@avil13 Repository is not available but it would be helpful if we can make a short call and look at it together.

**Comment by avil13** [comment]
@Stehos sorry, there will be problems with this)

**Comment by christopher4lis** [comment]
I have the same issue here when integrating w/ nuxt–seems like the styles are all being inlined by default.

**Comment by jripmeester** [comment]
Same issue here. Anyone solved this?
