### ISSUE TITLE
[Nuxt] Methods (such as isLoading, showValidationMessage, etc.) showing "is not a function" on Nuxt

### ISSUE THREAD

**Issue by ZeyadAmr** [avil13/vue-sweetalert2#120]
[codesandbox example](https://codesandbox.io/s/eager-river-8bs2h?file=/pages/index.vue)

I am using the same code that I have used on a previous **Vue** project (vue-sweetalert2 3.0.5), however, when I try to run it on Nuxt I get the error message:

```Uncaught (in promise) TypeError: _this2.$swal.showValidationMessage is not a function```
same with .isLoading and others.

  - Version: 4.1.1 (latest as of date)

**Comment by avil13** [comment]
@ZeyadAmr Thank you for the example, I will try to check this error soon.

**Comment by darkons** [comment]
I'm having the same problem

Any news about this bug?

**Comment by adrian-webgurus** [comment]
Hey @avil13, any news about this bug?

**Comment by avil13** [comment]
I just found time to come back to this issue.
Started to do everything from the beginning.

```sh
yarn create nuxt-app some-app-name # Here I chose the typescript option
cd some-app-name
yarn
yarn add vue-sweetalert2
```
Then did this

https://github.com/avil13/vue-sweetalert2#add-types-to-typescript-project
https://github.com/avil13/vue-sweetalert2#nuxtjs

Then I wrote a method in `index.vue`:
```html
<template>
<a href="" class="button--grey" @click.prevent="alert">
 alert
</a>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  methods: {
    alert () {
      this.$swal('Alert!');
    }
  }
});
</script>
```

I'm sorry, but everything works for me.
