### ISSUE TITLE
[Nuxt] fire is not a function

### ISSUE THREAD

**Issue by mushonnip** [avil13/vue-sweetalert2#121]
I import the lib 
`import Swal from 'vue-sweetalert2/nuxt'`
and got this error while using Swal.fire()
`vue_sweetalert2_nuxt__WEBPACK_IMPORTED_MODULE_7___default.a.fire is not a function`

**Comment by galaczi** [comment]
You should use it like this:

`      this.$swal('Hello Vue world!!!');`
