### ISSUE TITLE
How can i use this in vue 4 at global?

### ISSUE THREAD

**Issue by ozgurkaracam** [avil13/vue-sweetalert2#127]
Hello, i try use in vue 4 this.

i can't use Vue.swal(), 'Vue is not defined.',

i tried in store vuex. pleasehelp me

**Comment by avil13** [comment]
Hi.  It seems to me that you absolutely do not understand what you are doing.  Try to read the documentation for the framework.  Vue4 doesn't exist at the moment.  Try to post this comment in 5 years.

**Comment by avil13** [comment]
Have you read the issue template?
