### ISSUE TITLE
Show Loading not working when installing with options

### ISSUE THREAD

**Issue by allestaire** [avil13/vue-sweetalert2#128]
```js
import VueSweetalert2 from 'vue-sweetalert2';
import 'sweetalert2/dist/sweetalert2.min.css';
Vue.use(VueSweetalert2, {
	confirmButtonColor: 'red',
});
```
With this, the **this.$swal.showLoading()** will not be available, can someone pin point on how to add the option without losing other functionality?

**Comment by avil13** [comment]
@allestaire I'm sorry. But the function in the current v4.2 version works.
Or did I get something wrong?

**Comment by allestaire** [comment]
Did you try to install the package with options? In my case, installing the package with options will disable the showLoading method, dont know why :(. Still thanks for the response

**Comment by avil13** [comment]
@allestaire here is an example
https://codesandbox.io/s/eager-elgamal-efnyk

**Comment by allestaire** [comment]
Hmm I see it work well on your end, I try to check it on my end, thanks for the response it helps alot. :)
