### ISSUE TITLE
Background color change nuxtjs

### ISSUE THREAD

**Issue by nickelnext** [avil13/vue-sweetalert2#129]
## 👋 Good day

Hi.

In nuxt.js project I have
modules: 
```
 [
      'vue-sweetalert2/nuxt',
      {
        confirmButtonColor: '#ff0000',
        cancelButtonColor: '#0000ff',
      }
    ]
```

I want to either use the dark-theme (which i already installed with 
`npm install --save sweetalert2 @sweetalert2/theme-dark`

or just be able to set the background of the alerts to a custom color.
How can I achieve that? It is not clear to me.

Thank you very much

**Comment by avil13** [comment]
Hi. Here is a sample solution, added in version 4.2.1

https://github.com/avil13/vue-sweetalert2#using-a-different-theme-in-nuxt

**Comment by nickelnext** [comment]
Thanks!! you're great!
