### ISSUE TITLE
How is the best method to updating Swal in Laravel Project?

### ISSUE THREAD

**Issue by obink** [avil13/vue-sweetalert2#130]
this is not an issue, it's just a request to get a clean update for **swal in running Laravel Project**. Currently my project is running good but some featured updates required a new swal.

SweetAlert2: Unknown parameter "showDenyButton"

please help and advice.

**Comment by avil13** [comment]
Hi.
How exactly does your library get built?
Do you use _webpack_, _gulp_ or something else to build it?
And what happens if you just do 
`yarn add vue-sweetaler2` ?

I just can't figure out how everything works and what the problem is.

**Comment by avil13** [comment]
Closing, as there is no answer for a long time
