### ISSUE TITLE
[Nuxt] Support top level option

### ISSUE THREAD

**Issue by mrleblanc101** [avil13/vue-sweetalert2#132]
Hi,
Would it be possible to support top-level option as well as module option in Nuxt ?
This would be much cleaner for people that have a lot of Nuxt module.
https://nuxtjs.org/docs/2.x/directory-structure/modules/

Currently I have to set options like so:
```
modules: [
    ['vue-sweetalert2/nuxt', {
            customClass: {
            container: 'theme-custom',
            confirmButton: 'button primary',
            cancelButton: 'button secondary'
        },
        buttonsStyling: false
    }],
],
```
And with top-level options we could do something like this:
```
modules: [
    'vue-sweetalert2/nuxt'
],

sweetalert: {
    customClass: {
        container: 'theme-custom',
        confirmButton: 'button primary',
        cancelButton: 'button secondary'
    },
    buttonsStyling: false
}
```

## I also want to know

  - Version: 4.2.1
  - Platform: macOS
  - Subsystem: 11.1

**Comment by mrleblanc101** [comment]
I could probably make a PR myself for this if I have the go-ahead

**Comment by avil13** [comment]
Haven't worked with nuxt in a long time, and it will be interesting to see how this can be implemented. Thanks.
If there is a PR, I would be happy to discuss it.
