### ISSUE TITLE
Module display flex instead of grid

### ISSUE THREAD

**Issue by Oktogazh** [avil13/vue-sweetalert2#137]
## 👋 Hello

First, thank you for you work!
I couldn't reproduce the bug on code sandbox but here is my issue:

For some reason, my alerts display flex instead of grid: 

![image](https://user-images.githubusercontent.com/69036359/121773751-2448ca00-cb7e-11eb-85aa-1a8b6c77037d.png)

which causes the elements to be displayed horizontally.

The problem doesn't occur with the original sweetalert2 module, and I have no idea what's causing it.
Also it might be worth mentioning that I checked out previous commits and the problem persisted, while it wasn't here previously, it may be linked to a recent update, cause I hadn't the problem a month ago.
So yes, it's a weird bug, and your code might not be responsible, yet it only occurs on this vue plugin.

  - Version: 4.3.1
  - Platform: Kubuntu 20.04

**Comment by saadabdurrazaq** [comment]
Same here

**Comment by avil13** [comment]
@Oktogazh  @saadabdurrazaq 
Hi. 
Can you add styles to this example?
Because I don't really understand what needs to be fixed.

https://stackblitz.com/edit/vue-9e8haq?file=src/App.vue

**Comment by Oktogazh** [comment]
Hello @avil13,
I was going to answer you that style doesn't matter since everything (except the root component) is scoped.
But then I checked your example on stackblitz... and I get the same horizontal display:
![image](https://user-images.githubusercontent.com/69036359/122678619-db30ef80-d1e7-11eb-9ad8-83ab53541d96.png)
Both on Firefox and Chrome, didn't you clicked the button yourself or am I missing something? :sweat_smile:

**Comment by saadabdurrazaq** [comment]
@avil13 I just import `'sweetalert2/dist/sweetalert2.min.css' `. If I don't import it, the modal can't be displayed, but if I import it, my alert display flex instead of grid.

**Comment by avil13** [comment]
A new version of the library came out, I need to update too. Maybe that's the problem

**Comment by avil13** [comment]
@saadabdurrazaq @Oktogazh 
I updated the library to version 5 please check how it works
https://stackblitz.com/edit/vue-9e8haq?file=src%2Fmain.js

**Comment by Oktogazh** [comment]
I didn't try on my app app yet, but it works like a charm even on the link you publish 10 days ago.
So the issue seems to be solve, well done!
I think you can close the this.
@saadabdurrazaq do you concur?

**Comment by Qblack** [comment]
For those who find this and updating does not seem to work adding 
```css
.custom-swal-grid {
  display: grid !important;
}
```
and

```js
        customClass: {
          popup: 'cat-swal-grid'
        },
```
will atleast make it go vertical.

**Comment by tim330i** [comment]
I'm still having this problem using version 11.  I'm adding SweetAlert2 to an existing website, and I'm unsure how to resolve the CSS conflict that is changing the style from grid to flex.

Tim
