### ISSUE TITLE
Amazon Web Services?

### ISSUE THREAD

**Issue by LeYvan** [avil13/vue-sweetalert2#14]
It seems this npm package has an indirect dependencie to amazon web services ([aws4](https://www.npmjs.com/package/aws4)) I am confused has to why this is? Discard this issue if I was wrong, but it has me worried and I consequently decided against using it because of that.

Am I being paranoid?

**Comment by avil13** [comment]
Good afternoon.
Thank you for your attention, I did not notice this.
Perhaps this is somehow related to yarn.
Or something in the library sweetalert2.
It is necessary to look more attentively.
Thank you for your comment.

**Comment by avil13** [comment]
aws is found in the "fileset" package
Most likely this is some sort of dependence in the library and I can not influence it.
Thank you once again for your care.
