### ISSUE TITLE
Style not applied in Nuxtjs 2

### ISSUE THREAD

**Issue by asoko2** [avil13/vue-sweetalert2#146]
I have followed all the steps to install vue-sweetalert2 in Nuxt.js, but the style won't applied , 

I've tried to import the css file manually, but it won't do something

**Comment by avil13** [comment]
Good afternoon.
Can you find out the Nuxt version more accurately?
Even within the minor edits, there may have been changes

**Comment by avil13** [comment]
Hi.
Is the problem still relevant?
Or did you manage to look at the README file and solve everything?

**Comment by asoko2** [comment]
I'm sorry, i didn't have time to open it yesterday, 
yes the problem still relevant, i'm using Nuxt 2.15.8,

and here is how it's look like, 

![swal ](https://user-images.githubusercontent.com/29307687/169482246-55123750-a399-45d8-b7be-aeeab7daa165.png)

**Comment by avil13** [comment]
You wrote that the styles don't apply.
But the screenshots show an alert with the right styles.
Can you elaborate a little more on what's wrong?

**Comment by avil13** [comment]
I copied your repository, https://github.com/asoko2/pelam-ui
Checked it, and everything works as it should.

**Comment by avil13** [comment]
Off-topic.
I would recommend looking in the direction of Nuxt 3.
You can use sweetalert2 there - without the wrapper.

I'm closing Issue, because it's not relevant.

Good luck with your projects.
