### ISSUE TITLE
Inertiajs: Cannot read properties of undefined (reading '$swal')

### ISSUE THREAD

**Issue by datlechin** [avil13/vue-sweetalert2#147]
**Describe the bug**
The console say `Uncaught TypeError: Cannot read properties of undefined (reading '$swal')`

Here is my `app.js` code:

```js
import { createApp, h } from 'vue'
import { createInertiaApp } from '@inertiajs/inertia-vue3
import VueSweetalert2 from 'vue-sweetalert2';

createInertiaApp({
    resolve: name => require(`./pages/${name}`).default;
    setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(VueSweetalert2)
            .mount(el)
    },
})
```

**I also want to know**
  - Version: Latest
  - Platform: Inertiajs

**Comment by avil13** [comment]
Hi.  
Is your repository closed or can I see the whole code?  
Also, there is a moment.  
You are using Vue3.  And in the "setup" method, no context is passed there.  That's why you got this error. 
 And so you can use sweetalert2 - without a wrapper.

**Comment by datlechin** [comment]
@avil13 Here is my code

```js
import {Link, useForm} from "@inertiajs/inertia-vue3";
import Layout from "./Layout";

export default {
    components: {
        Layout,
        Link
    },
    props: {
        transfers: Object
    },
    setup() {
        const form = useForm({
            receiver: '',
            amount: '',
            description: ''
        })

        const submit = () => {
            form.post('/user/transfer', {
                onSuccess: () => {
                    form.reset()
                    this.$swal('Testing')
                }
            });
        }

        return {form, submit}
    }
}
```

**Comment by avil13** [comment]
This is not a bug.

I added some comments on your code.

```ts
export default {
    // ...
    setup() {
        const form = useForm({
            receiver: '',
            amount: '',
            description: ''
        })

        const submit = () => {
            form.post('/user/transfer', {
                // since it is an arrow function, it will take the context from the setup method
                // just a warning so you don't write onSuccess() {...} - otherwise the context of this will be different
                onSuccess: () => { 
                    // here this is the context from setup
                    // but since this in setup === undefined - you get an error.
                    this.$swal('Testing')
                }
            });
        }

        return {form, submit}
    }
}
```

To see what I mean, you can check [this example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cblxuICBjb25zdCB0eXBlT2ZDdHggPSB0eXBlb2YgdGhpcztcbiAgXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cHJlPnt7IHR5cGVPZkN0eCB9fTwvcHJlPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=).


I wrote above, it would help you to use Sweetalert2 without the wrapper, in Vue3 - it doesn't make sense anymore.

```ts
form.post('/user/transfer', {
    onSuccess: () => { 
        Swal.fire('Testing')
    }
});
```

Thanks for the comments, and good luck with the code)))

**Comment by datlechin** [comment]
Thank you, it works very well with Sweetalert2 without wrapper
