### ISSUE TITLE
Security issue on SweetAlert2

### ISSUE THREAD

**Issue by Snicser** [avil13/vue-sweetalert2#149]
Hi,

I just got a notification from my DependaBot about this, under the hood this package is using 11.6.14 version? I am right? I think it is a good idea downgrade to this range if possible. And update to a higher version if the mainter fixed the issue. 

![image](https://user-images.githubusercontent.com/25828832/204154739-c1108180-e95b-4dd7-9ac0-ef9e152918f8.png)

**Comment by avil13** [comment]
Hi.
My library is just a wrapper over sweeatalert2.
And the author decided to take a different path, even if it goes against humanity.
I cannot condemn him.
But if I were you, I would look for another library.

https://github.com/sweetalert2/sweetalert2/commits/main/src/SweetAlert.js?author=limonte
<img width="624" alt="image" src="https://user-images.githubusercontent.com/1606172/204216613-de24f882-2750-4211-9da1-4dcf3e248f3a.png">

**Comment by Snicser** [comment]
Ah okay, thanks for the information.

**Comment by avil13** [comment]
@Snicser Do you think it's worth making an alternative to this library, or are there already enough of these?

**Comment by Snicser** [comment]
Uhmm yes and no, I think if you take good approach to Developer Experience and implments everything well it would be a better package. I think you could this package 100% better.
