### ISSUE TITLE
how to bind html values to v-model and detect changes

### ISSUE THREAD

**Issue by raza2022** [avil13/vue-sweetalert2#15]
Hello @avil13 
I have just basic use case example in context of Vue. for ease am attaching the basic swal template which have html input values
https://codepen.io/raza2022/pen/pVmdXV
how I can bind that html values to v-model and detect change. I even tried with watch and made it computed property too. but nothing works
Any help will be greatly appropriated.

**Comment by avil13** [comment]
Hi.
I made the simplest preview, how you can get data and write it to Vue data.

Look and tell me if I answered your question?
And I wish you good luck.

[https://codepen.io/avil13/pen/qYGyQG](https://codepen.io/avil13/pen/qYGyQG)

**Comment by raza2022** [comment]
@avil13 Thanks for quick response :+1: 
I think I didn't deliver my exact question. actually I want to bind the v-model directly to sweetalert inputs so on every keyup or keypress within sweetalert input I can detect changes. for example
I want to get value from `v-model` directly from input instead of 
`document.getElementById('swal-input2').value`
I just want to know if that possible or not because it's looks like sweet alert inputs not behave as other inputs within templates. or am wrong?
Thanks

**Comment by avil13** [comment]
Sorry for the long answer. 
I think I found a possible solution to your problem, but It looks a little like a hack.

[https://codepen.io/avil13/pen/BxXXWL](https://codepen.io/avil13/pen/BxXXWL)

**Comment by raza2022** [comment]
ok my question is about directly attaching (v-model within swal) possibility. yes you comes with good hack so I think that solve for now Thank you so much :heart:

**Comment by avil13** [comment]
Unfortunately I don't know how to join an element outside the context of VueJs. 
But this solution, by VueJs in native JavaScript.
Good luck

**Comment by thEpisode** [comment]
Good solution, I have the same issue but I think is very tricky try to find a correct solution 🤔

**Comment by thEpisode** [comment]
In my case I use next code:
```
      const { value: dialogResult } = await Swal.fire({
        type: 'info',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, pay it!',
        target: document.querySelector('#vue-app'),
        html:
          `
          <div class="swal2-header">
            <h2 class="swal2-title" id="swal2-title">Please confirm and amount for payout</h2>
          </div>
          <div class="swal2-content">
            <input name="" v-model="vueBind.model.payout.amount" class="open-payout-input swal2-input">
            <div id="swal2-content">Warning: This payout will be charged immediately</div>
          </div>`,
          onOpen: () => {
          document.querySelector('.open-payout-input').addEventListener('input', this.openPayoutInputOnInput)
        },
        onClose: ()=>{
          document.querySelector('.open-payout-input').removeEventListener('input', this.openPayoutInputOnInput)
        }
      })
      console.log(this.vueBind.model.payout.amount)
....
.....
    openPayoutInputOnInput: function (event) {
      if (event.target.className.includes('open-payout-input')) {
        this.vueBind.model.payout.amount = event.target.value;
      }
    },
```

**Comment by ElizeuBraga** [comment]
I use didOpen

```
didOpen: () => {
          document.getElementById('swal-input1').value = this.name
},
```
