### ISSUE TITLE
ERROR Cannot restart nuxt: Cannot read properties of undefined (reading 'sweetalert')

### ISSUE THREAD

**Issue by TokyConstellation** [avil13/vue-sweetalert2#152]

**Comment by TokyConstellation** [comment]
nuxt 3

**Comment by avil13** [comment]
@TokyConstellation Hi.
I apologize, haven't updated the plugin under Nuxt 3.
I also plan to close this repository, as the author of sweetalert2 - has embedded malicious code in his library and does not plan to remove it.
I was hoping that something would be fixed, but nothing has changed.
Therefore, work on my wrapper will be stopped. I don't want users to be at risk.

Try to find another notification library.
