### ISSUE TITLE
this.$swal not work in VueJS 3 (script setup)

### ISSUE THREAD

**Issue by quinhone** [avil13/vue-sweetalert2#155]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$swal')

`authStore.login(values.email, values.password)
    .then( () => {
        router.push({ name: 'dashboard' })
    }).catch( () => {
        this.$swal('Hello Vue world!!!');
    })`

**Comment by avil13** [comment]
@quinhone Hi.
The setup method doesn't have "this", so I recommend using a simple import, without using $swal.
Also, I'd recommend looking for a different library.

**Comment by quinhone** [comment]
import Swal from 'sweetalert2'

Swal.fire( ) is work for me
