### ISSUE TITLE
Module import VueSweetalert2 from 'vue-sweetalert2' not found in main.js

### ISSUE THREAD

**Issue by jfnando3030** [avil13/vue-sweetalert2#158]
Hi, I updated this library to version 5.0.9 but I got the following error in the main.js file of my Vue 3 project 

 error  in ./src/main.js

Module not found: Error: Default condition should be last one

ERROR in ./src/main.js 20:0-45
Module not found: Error: Default condition should be last one

webpack compiled with 1 error

**Comment by avil13** [comment]
@jfnando3030 @nidebr  thank you. You can upgrade to version `5.0.10`
