### ISSUE TITLE
Some object properties not working?

### ISSUE THREAD

**Issue by dashc** [avil13/vue-sweetalert2#16]
So this works fine:
`this.$swal("Good job!", "You clicked the button!", "success")`

However as soon as I use an object some properties do not work:
`this.$swal({
      title: "Good job!",
      text: "You clicked the button!"",
      icon: "success",
    });`
In this case only the icon property didn't work. I have also had the same issue with `buttons` e.g. false and text.

**Comment by avil13** [comment]
Good afternoon.
I apologize for the long response.

You have an error in the transfer of the parsers.
You do not correctly indicate them.
There are extra quotes and commas.

https://codepen.io/avil13/pen/eKdJMb

**Comment by dashc** [comment]
Sorry that was a accident. If you look at your pen you sent me you will notice there isn’t an icon tick being shown for the success icon.

**Comment by avil13** [comment]
https://sweetalert2.github.io/ - in documentation we do not have option **icon**, but I find 
 **type: "_success_"** and  **imageUrl**.
