### ISSUE TITLE
Nuxt project build failed with: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './nuxt' is not defined by "exports" in vue-sweetalert2\package.json

### ISSUE THREAD

**Issue by kokhoor** [avil13/vue-sweetalert2#160]
**Describe the bug**
When building my nuxt project that includes vue-sweetalert2 using yarn, the build failed with following error:

 Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './nuxt' is not defined by "exports" in vue-sweetalert2\package.json
 
we import vue-sweetalert2 in nuxt.config.js:
modules: [
    // https://go.nuxtjs.dev/bootstrap
    "bootstrap-vue/nuxt",
    "vue-sweetalert2/nuxt"
  ],

 To fix it, I had to manually change:
 
 node_modules/vue-sweetalert2/package.json by adding:
 
"./nuxt": "./nuxt/index.js"

to:

"exports": {
    ".": {
      "import": "./dist/vue-sweetalert.mjs",
      "require": "./dist/vue-sweetalert.umd.js",
      "types": "./dist/index.d.ts",
      "default": "./dist/vue-sweetalert.js"
    },
    "./nuxt": "./nuxt/index.js"  // added this line
  }

If there is a solution where we don't have to change package.json will be ideal.

**I also want to know**
  - Version: vue-sweetalert@5.0.10, vue@^2.7.16
  - Platform: Windows

**Comment by davidVenegas** [comment]
Yes, I have the same problem but I can't change the package.json because I'm creating a docker image

**Comment by mohsin** [comment]
+1

**Comment by mohsin** [comment]
Same issue +1

**Comment by wanarsanPhaiii** [comment]
Same +1

**Comment by lifan2029** [comment]
Same +1

**Comment by avil13** [comment]
Hi all.
Nuxt support has been made for version 2.
It has not been added for v3 yet.
You can just use sweetalert2 as a hotel library.

**Comment by caglarduman** [comment]
Same +1 
It was working without any issues until now. As of this week, we started receiving this error.

"nuxt": "^2.15.7"
"vue-sweetalert2": "^5.0.2"

**Comment by avil13** [comment]
@caglarduman Update to the latest version. And if there is an error, please send the log.

**Comment by thanhdanh2604** [comment]
Hello, I encountered the same issue. I attempted to change my Node.js version from 18 to 16.20.2, and it resolved the error.

**Comment by caglarduman** [comment]
@avil13 

When I used the "^" symbol in the "vue-sweetalert2": "^5.0.2" line in the package.json, it automatically used version 5.0.10, which is the latest released version. I removed the "^" symbol and forced it to use version 5.0.2. The issue was resolved. I think the problem was in the latest version.

**Comment by avil13** [comment]
@caglarduman I apologize for taking so long. Can you look up version 5.0.11?

**Comment by avil13** [comment]
I guess we can close the discussion
