### ISSUE TITLE
conflict with vue-ssr

### ISSUE THREAD

**Issue by volkovmqx** [avil13/vue-sweetalert2#17]
can't use this package while using ssr.
this package uses the 'window' object

**Comment by avil13** [comment]
Hi.
Can you provide a link to the repository to check?
I doubt that will be able to solve this problem, but it's fun to see.

**Comment by volkovmqx** [comment]
basically use vue-sweetalert2 with this https://github.com/anthonygore/vue-js-laravel-multi-ssr

**Comment by avil13** [comment]
Now sweetalert2 does not support SSR.
But the developers are working on this. I do not know how to help yet.
In NuxtJS, this plan is referred to as not subject to SSR.
https://nuxtjs.org/guide/plugins#client-side-only
I will be glad if something changes.

**Comment by volkovmqx** [comment]
@avil13 unfortunately we switched to nuxt, and basically implemented this using plugins.

**Comment by avil13** [comment]
@volkovmqx Excellent solution. 
Still a little sorry I didn't get help in time. 
And what is not clear is whether everywhere my patch works effectively for SSR. 
Anyway, thanks for the support.
