### ISSUE TITLE
Error :  __WEBPACK_IMPORTED_MODULE_3_vue_sweetalert2__.a.queue is not a function

### ISSUE THREAD

**Issue by erwin16** [avil13/vue-sweetalert2#18]
trying to test one the examples in my Vue component Profile.vue  , i get an error

Profile.vue

    `const ipAPI = 'https://api.ipify.org?format=json'
      swal.queue([{
        title: 'Your public IP',
        confirmButtonText: 'Show my public IP',
        text:
          'Your public IP will be received ' +
          'via AJAX request',
        showLoaderOnConfirm: true,
        preConfirm: () => {
          return fetch(ipAPI)
            .then(response => response.json())
            .then(data => swal.insertQueueStep(data.ip))
            .catch(() => {
              swal.insertQueueStep({
                type: 'error',
                title: 'Unable to get your public IP'
              })
            })
        }
      }])`
     

console.log 

    `Profile.vue?5da6:123 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_3_vue_sweetalert2__.a.queue is not a function
    at VueComponent.editPhotoUrl (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"/Users/myproject/node_modules/.cache/cache-loader"}!./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Member/Profile.vue`

**Comment by avil13** [comment]
Hello, you too.

Example from documentation.
But in my cases, mixing not working. I don't know why.

swal.mixin({
  input: 'text',
  confirmButtonText: 'Next &rarr;',
  showCancelButton: true,
  progressSteps: ['1', '2', '3']
}).queue([
  {
    title: 'Question 1',
    text: 'Chaining swal2 modals is easy'
  },
  'Question 2',
  'Question 3'
]).then((result) => {
  if (result.value) {
    swal({
      title: 'All done!',
      html:
        'Your answers: <pre><code>' +
          JSON.stringify(result.value) +
        '</code></pre>',
      confirmButtonText: 'Lovely!'
    })
  }
})
