### ISSUE TITLE
Latest version breaks my app

### ISSUE THREAD

**Issue by mrdigitalau** [avil13/vue-sweetalert2#21]
Hey guys
Thanks for your hard work with this.
Just so you know, I used Vue Sweetalert2 on another app and worked fine in IE11, it was version 1.4.2.
I just recently installed 1.5.0 in a new application and it would not working in IE11, even with Babel Polyfill.

The error was specifically because of this extra code:

Line 10 of index.js, 

From VueSweetalert2.install = function(Vue) {

To `VueSweetalert2.install = function(Vue, options = { toast: false }) {`
   
I had to downgrade to 1.4.2 for it to work again, is there some sort of extra polyfill we need for this to work?
Cheers

**Comment by avil13** [comment]
Hi. Try version 1.5.1 in it I fixed this line. Write as check, if not difficult. Thanks.

**Comment by mrdigitalau** [comment]
Thanks so much Alexey, you saved me :)
Cheers, I just upgraded it to 1.5.1
Thank you for your time sir
