### ISSUE TITLE
Use Minify Please

### ISSUE THREAD

**Issue by muhibbudins** [avil13/vue-sweetalert2#24]
Hi @avil13 ,

Why you use "all" version of SweetAlert? Not a minify version?

https://github.com/avil13/vue-sweetalert2/blob/e6fec5467895535b7236954f988178c20b2bc5d5/src/index.js#L2

---

Your bundle will more efficient, if you use a minify version like this.

```js
// @ts-check
import swal from 'sweetalert2/dist/sweetalert2.min.js';
import 'sweetalert2/dist/sweetalert2.min.css';
```

Thank you

**Comment by avil13** [comment]
Thanks, I'll fix it 👍

**Comment by muhibbudins** [comment]
Okey thank you @avil13 👍
