### ISSUE TITLE
Typescript Error - Cannot use namespace 'swal' as a type

### ISSUE THREAD

**Issue by LuckyURE** [avil13/vue-sweetalert2#26]
**Error received:**

> ERROR in c:/Users/my-name/workspace/Apps/Client/node_modules/vue-sweetalert2/src/index.d.ts
> 6:25 Cannot use namespace 'swal' as a type.
>     4 | // declare function swal(title: string, message?: string, type?: SweetAlertType): Promise<any>;
>     5 |
>   > 6 | declare type swalFunc = swal;
>       |                         ^
>     7 |
>     8 | declare module 'vue/types/vue' {
>     9 |     interface Vue {
> ERROR in c:/Users/my-name/workspace/Apps/Client/node_modules/vue-sweetalert2/src/index.d.ts
> 10:16 Cannot use namespace 'swal' as a type.
>      8 | declare module 'vue/types/vue' {
>      9 |     interface Vue {
>   > 10 |         $swal: swal; // () => Promise<any>;
>        |                ^
>     11 |     }
>     12 | }
>     13 |
> ERROR in c:/Users/my-name/workspace/Apps/Client/node_modules/vue-sweetalert2/src/index.d.ts
> 16:16 Cannot use namespace 'swal' as a type.
>     14 | declare module 'vue/types/options' {
>     15 |     interface ComponentOptions<V extends Vue> {
>   > 16 |         swal?: swal; // () => Promise<any>;
>        |                ^
>     17 |     }
>     18 | }

**Steps taken:**

1) yard add vue-sweetalert2
2) main.ts -> added the following:
    import VueSweetalert2 from "vue-sweetalert2";
    Vue.use(VueSweetalert2);

As soon as I save, the vue cli compiles and spits out the errors provided above.

I'm using version: **"vue-sweetalert2": "^1.5.6"**

Thank you for your time and consideration.

**Comment by avil13** [comment]
Can you give me your `tsconfig.json`?

**Comment by LuckyURE** [comment]
Sure, here it is:

{
"compilerOptions": {
"target": "esnext",
"module": "esnext",
"strict": true,
"jsx": "preserve",
"importHelpers": true,
"moduleResolution": "node",
"experimentalDecorators": true,
"esModuleInterop": true,
"allowSyntheticDefaultImports": true,
"sourceMap": true,
"baseUrl": ".",
"types": [
"webpack-env"
],
"paths": {
"@/*": [
"src/*"
]
},
"lib": [
"esnext",
"dom",
"dom.iterable",
"scripthost"
]
},
"include": [
"src/**/*.ts",
"src/**/*.tsx",
"src/**/*.vue",
"tests/**/*.ts",
"tests/**/*.tsx"
],
"exclude": [
"node_modules"
]
}

**Comment by avil13** [comment]
I added an example to the `example` folder.

Pay attention to `webpack.config.js` and the file` tsconfig.json`.

**Comment by avil13** [comment]
https://github.com/avil13/vue-sweetalert2/tree/master/example

**Comment by dukemike** [comment]
@LuckyURE, did you resolve this? I'm getting the same and my `tsconfig.json` looks right to me but I'm far from an expert.

**Comment by LuckyURE** [comment]
Hi Mike, no didn't really try.. switched to a different library that works
just fine for my needs 'unfortunately'.

**Comment by avil13** [comment]
@dukemike Try version `1.5.10`, please.
I want to correct this error, this is a matter of principle.

**Comment by dukemike** [comment]
@avil13 Sorry for the delayed response. I created a new project using Vue CLI 3, added `vue-sweetalert2@1.5.11` and the sample code into the App.vue.

When using, `this.$swal`, I receive the Javascript error `Cannot read property '$swal' of null` when clicking the button. When attempting to use `Vue.swal()` yarn fails with `Property 'swal' does not exist on type 'VueConstructor<Vue>'.`.

What can I do to help?

[package.json.txt](https://github.com/avil13/vue-sweetalert2/files/2691099/package.json.txt)
[tsconfig.json.txt](https://github.com/avil13/vue-sweetalert2/files/2691100/tsconfig.json.txt)
[App.vue.txt](https://github.com/avil13/vue-sweetalert2/files/2691102/App.vue.txt)

**Comment by dukemike** [comment]
Thanks!
