### ISSUE TITLE
Cannot resolve vue-sweetalert2/nuxt

### ISSUE THREAD

**Issue by melokki** [avil13/vue-sweetalert2#34]
Hello.
I am trying to use this package with nuxt, but after I followed the instruction from the readme I get the following error

```
fatal Error: Cannot resolve "vue-sweetalert2/nuxt"
```
I looked in `node_modules/vue-sweetalerts2` and I see that there is no `nuxt` folder in there. Am I missing something?
the support for nuxt is not released yet?

**Comment by avil13** [comment]
I fixed this error. Write if you still have problems.
