### ISSUE TITLE
`toast`s are blocking page

### ISSUE THREAD

**Issue by AmirrezaNasiri** [avil13/vue-sweetalert2#36]
Hi,

I have problem manipulating `toast` option on `vue-sweetalert2` version 1.5.9 which causes entire page to be blocked until timeout is reached. Here is a simple config:

```
this.$swal({
	toast: true,
	position: 'top-end',
	showConfirmButton: false,
	timer: 10000,
	type: 'success',
 	text: 'Sorry, you have no choice but to wait 10 seconds!',
});
```

Compare the behaviour with the original Sweetalert2 pen in which is non-blocking:

https://codepen.io/amirrezanasiri/pen/RqYyqN

Please let me know if I should give anything else about the problem I face.

**Comment by avil13** [comment]
Thank you for using this library.

Your problem belongs to the sweetalert2 library itself. I just made a handy wrap for Vue.

I tried to repeat your problem, but I have not observed it.

Can you see how our examples differ?

Added a line to deactivate the absence of a browser lock.

Maybe it's in the very moment of creating a mixin?

https://codesandbox.io/s/v0xw6v0575

**Comment by AmirrezaNasiri** [comment]
Thank you so much for your quick reply! this is valuable.
`$swal.mixin` has solved the problem. I'm going to close this issue.
