### ISSUE TITLE
Question: Is there a way to inject defaults somewhere?

### ISSUE THREAD

**Issue by ImreC** [avil13/vue-sweetalert2#37]
Title pretty self explanatory

**Comment by avil13** [comment]
Default swal?

Of course. 
```js
<script>
import swal from 'sweetalert2/dist/sweetalert2.min.js';
import 'sweetalert2/dist/sweetalert2.min.css';

export default {
  mounted() {
    swal('Hello world');
  }
}
</script>
```

**Comment by ImreC** [comment]
Ok apparently not that self explanatory. I am using a nuxt app. Can I pass global config for swal somewhere? I am trying $swal.mixin in numerous locations, but to no avail. Preferably would want to do this on server init or via nuxt.config.js.
