### ISSUE TITLE
Question: Is there a way to inject defaults somewhere? 

### ISSUE THREAD

**Issue by ImreC** [avil13/vue-sweetalert2#38]
Apologies for the last question, apparently it was not that self-explanatory. I am using a nuxt app. Can I pass global config for swal somewhere? I am trying $swal.mixin in numerous locations, but to no avail. Preferably would want to do this on server init or via nuxt.config.js.

**Comment by avil13** [comment]
You may need to create a plugin for Nuxt.
Check out the Nuxt documentation for this. Right now I can not help you, but it is possible.

**Comment by avil13** [comment]
I had an idea for generating mixins in a similar way.

But he didn’t do it, because it’s not clear whether the developer needs it.

Now there is a clean wrap over Sweetalert2.
You can try to add this API.
If it is useful, then add to the master branch.

**Comment by ImreC** [comment]
Created a pull request with Nuxt options and Vue options for global defaults. I didn't update ts definitions, because I don't know typescript. @avil13 can you review and merge?

**Comment by avil13** [comment]
Had the idea to change it a bit. I want to consult.

`this.$swal` - this is a common function for creating alert.

What to do if the ability to create multiple prepared `alert` or `toast` messages?


```js
const options = {
    mixins: {
        // key for alert
        goodAlert: {
            type: 'success',
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000
        }
    }
};

Vue.use(VueSweetalert2, options);
```

```js
// use in vue component
export default {
    methods: {
        alert() {
            // key for alert
            this.$swal.goodAlert('Hello world');
        }
    }
}

```

**Comment by ImreC** [comment]
My first thought was that passing global options only is better because you usually end up requiring some minor details to change anyway and end up having a set of standard messages that you don't use. On the other hand, for some use cases it would be better to have a set of standard alerts ready. I am not sure. Maybe try the simple one first and add more complexity if other people ask for the second feature? The pull request I created covers my personal use case.

**Comment by avil13** [comment]
I apologize for such a long wait for merge.
https://github.com/avil13/vue-sweetalert2/pull/39

**Comment by realtebo** [comment]
Please, document this !

**Comment by fabriciozeferino** [comment]
> Thanks for the pull request.
> 
> Had the idea to change it a bit. I want to consult.
> 
> `this.$swal` - this is a common function for creating the alert.
> 
> What if given the opportunity to create several prepared `alert` or` toast` messages?
> 
> ```js
> const options = {
>     mixins: {
>         // key for alert
>         goodAlert: {
>             type: 'success',
>             toast: true,
>             position: 'top-end',
>             showConfirmButton: false,
>             timer: 3000
>         }
>     }
> };
> 
> Vue.use(VueSweetalert2, options);
> ```
> 
> ```js
> // use in vue component
> export default {
>     methods: {
>         alert() {
>             // key for alert
>             this.$swal.goodAlert('Hello world');
>         }
>     }
> }
> ```

Is this ideia working? I'm trying to implement and it says: 

`SweetAlert2: Unknown parameter "mixins"`

**Comment by Tragio** [comment]
@avil13 thank you very much for your awesome work. 🙂 

I would love to know how can we create mixins using your plugin. The official documentation says the following: " You can easily reuse configuration by creating your own `Swal` with `Swal.mixin({ ...options }):`"

However, not sure how can we create them and execute them globally.

Really thank you and keep the good work 😄
