### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by BloodSucker123** [avil13/vue-sweetalert2#45]
Why I can't use this plugin?
It has error while importing.
Im using browserify with vueify
![screen shot 2019-02-19 at 10 21 59 am](https://user-images.githubusercontent.com/41031355/52985802-51fb2980-3430-11e9-8903-74fab4e48a28.png)
![screen shot 2019-02-19 at 10 24 05 am](https://user-images.githubusercontent.com/41031355/52985850-8373f500-3430-11e9-8b17-cf18a25ec98c.png)

I also check the files on this plugin upon installing, but it has only few files.
![screen shot 2019-02-19 at 10 23 18 am](https://user-images.githubusercontent.com/41031355/52985872-9dadd300-3430-11e9-8912-992771d7aec5.png)

**Comment by avil13** [comment]
Hi.
Your repository is hidden? 
I have never used gulp-browserify so I just can't repeat your mistake.

**Comment by avil13** [comment]
Since I have not received any answer, we will assume that the question has been resolved.
