### ISSUE TITLE
[Question] Sweet Alert v8.0.0 breaking changes

### ISSUE THREAD

**Issue by Taxman972** [avil13/vue-sweetalert2#46]
The latest version of Sweet Alert comes with [many breaking changes](https://github.com/sweetalert2/sweetalert2/releases/tag/v8.0.0).
Do this package support them ?

**Comment by avil13** [comment]
Thanks for the link. Need to upgrade. As long as my version supports sweetalert v7.

**Comment by avil13** [comment]
`npm i vue-sweetalert2@beta` - while still in development
