### ISSUE TITLE
Can we have UMD version for direct browser use?

### ISSUE THREAD

**Issue by rosdi** [avil13/vue-sweetalert2#47]
Perhaps a CDN link for us non SPA developer would be nice.

**Comment by avil13** [comment]
I did not think about that. But try to do it, I think I can.

**Comment by cornernote** [comment]
I tried this, but doesn't work :(

https://cdn.jsdelivr.net/npm/vue-sweetalert2

**Comment by FM1337** [comment]
any updates on this?

**Comment by avil13** [comment]
Hi all. I think you can try version 5, if anyone is still interested)))
