### ISSUE TITLE
nuxt ^2.4.0 global option not working.

### ISSUE THREAD

**Issue by bawonsak** [avil13/vue-sweetalert2#53]
I pass global option in nuxt.config.js but it not working.

![Untitled](https://user-images.githubusercontent.com/13921255/58112750-521ce800-7c1e-11e9-82ad-b6355ed1e625.png)

![Untitled](https://user-images.githubusercontent.com/13921255/58112888-990add80-7c1e-11e9-83d2-17b9b828e04a.png)

**Comment by GodLikeZeal** [comment]
hello! I have a problem similar to yours. Have you solved it yet?
