### ISSUE TITLE
How to use when passing options?

### ISSUE THREAD

**Issue by realtebo** [avil13/vue-sweetalert2#55]
We can 

   this.$swal('Hello Vue world!!!');

But how can we pass, for example this ?

    { toast: true } 

I tried manually using the `.fire()` method 

    this.$swal.fire({
                title: this.title,
                type: this.type,
                toast: true
    });

but 

    this.$swal.fire is not a function

**Comment by jordanboston** [comment]
Try using just:
```
this.$swal({
            title: this.title,
            type: this.type,
            toast: true
});
```
