### ISSUE TITLE
Close sweetalert

### ISSUE THREAD

**Issue by neelbhanushali** [avil13/vue-sweetalert2#58]
How do you close a sweetalert using js?

**Comment by Grandizer** [comment]
Yes, I want to know this as well.  I upgraded from 1.5 to 2.0.5 and now close does not work.

We initially had:

```

this.$swal({
  title: '<i class="far fa-spin fa-spinner"></i>',
  text: text,
  showCancelButton: false,
  showConfirmButton: false,
  showCloseButton: false,
  allowOutsideClick: false,
  allowEscapeKey: false,
  allowEnterKey: false,
});
```
And then once the save was finished we would call:
```
this.$swal.close();
```
Since the update, now I get the error:
```
Uncaught (in promise) TypeError: this.$swal.close is not a function
```

**Comment by avil13** [comment]
This is because sweetalert2 v.8 changed their API.
To solve this problem, I did not find the time.
I apologize for that.

**Comment by Grandizer** [comment]
Understood.  I get we are all busy and I thank you for your time to get us this far.  Do you have a guestimate of when you will be able to get the time?

**Comment by neelbhanushali** [comment]
Please don't close the issue. Let it be open.

It will keep you posted that this is a good feature to be included in the plugin.

**Comment by Grandizer** [comment]
@neelbhanushali - I installed the 2.1.0 (the latest) and it works as it should again with the following code to use javascript to close a popup.

`this.$swal.close();`

**Comment by neelbhanushali** [comment]
I shall update the plugin. Thanks @Grandizer @avil13

**Comment by neelbhanushali** [comment]
I checked after updating the plugin. It works.

@avil13 you can close this issue. :)

**Comment by avil13** [comment]
Thank you all

**Comment by jonalxh** [comment]
Not working for me on 3.0.6 version, it throws the same error and doesn't let me close it programmatically.

**Comment by elguja** [comment]
@jonalxh Same here, Did you find solution?

**Comment by jonalxh** [comment]
@elguja No, I've just downgraded it to 3.0.4

**Comment by mhmdunl1** [comment]
You should import like this first

` import Swal from 'sweetalert2'`

Then you can close sweetalert in js like this.

`Swal.close()`
