### ISSUE TITLE
Custom Styles not working after update

### ISSUE THREAD

**Issue by harishkumar574** [avil13/vue-sweetalert2#60]
I previously used confirmButtonClass which worked before and not working after the update.

```
const options = {
	buttonsStyling: false,
	confirmButtonClass: 'btn white-text error',
	cancelButtonClass: 'btn white-text success'
}
Vue.use(VueSweetalert2, options)
```

I also tried this but still not working:

```
const options = {
	customClass: {
		confirmButton: 'v-btn white--text success',
		cancelButton: 'v-btn white--text error',
	},
	buttonsStyling: false,
}
Vue.use(VueSweetalert2, options)
```

What is the issue after update? am i missing something?

**Comment by jordanboston** [comment]
I just setup this in my project, and it works fine, but I am also not able to alter anything by passing in the options.  Not sure if it needs something else or if it is just broken right now.

**Comment by harishkumar574** [comment]
@jordanboston Yes, that is the issue here. Unable to use options.

**Comment by picbenoit** [comment]
Same for me, 

```
Vue.use(VueSweetalert2, {
    cancelButtonText: "Annuler"
});
```

But the cancel button still is "Cancel".

Is it a bug from last version ?

**Comment by phlegx** [comment]
I have the same problem! Any idea how to solve this bug?

**Comment by picbenoit** [comment]
Waiting a correction, you can add do like :

window.Swal = require('sweetalert2/dist/sweetalert2.js'); // Without CSS (add it one your sass build)
```
Vue.use({
    install(Vue, options) {
        let mySwal = Swal.mixin({
            cancelButtonText: "Annuler",
            showCancelButton: true
        });
        Vue.prototype.$swal = mySwal.fire.bind(mySwal);
    }
});
```

**Comment by jordanboston** [comment]
I'm wondering if this was a bug and if there is a solid fix for it, since I have not been able to set styles the way the documentation shows to?  Any news on this?

**Comment by avil13** [comment]
Sorry. How do you connect styles? Today I removed this option, and now it is necessary to connect the individual import

**Comment by jordanboston** [comment]
Like this:

const alertOptions = {
  confirmButtonText: 'Confirm',
  confirmButtonColor: '#4BAECC',
  cancelButtonColor: '#fde06e'
}
// Plugin installation
Vue.use(VueSweetalert2, alertOptions)

**Comment by avil13** [comment]
Need a debug sweetalert library.  Now in version v2.1.0 Vue-sweetalert2 this should work.  I am again far from the computer, but thanks I need reopen issue

**Comment by phlegx** [comment]
Upgrade to v2.1.0 don't solves the problem. I install `vue-sweetalert2` with options defined in `sweetalert2` v8.x from here [sweetalert2.github.io/#configuration](https://sweetalert2.github.io/#configuration):

```js
Vue.use(VueSweetalert2, {
  buttonsStyling: false,
  customClass: {
    confirmButton: 'btn btn-primary',
    cancelButton: 'btn btn-warning',
  }
})
```

**Comment by jordanboston** [comment]
Works for me now in v2.1.1 . --Thanks @avil13 !
