### ISSUE TITLE
Could not find a declaration file for module 'sweetalert2/dist/sweetalert2.min.js'

### ISSUE THREAD

**Issue by erickAvSanti** [avil13/vue-sweetalert2#61]
I have this error, how to solve ?

ERROR in /home/erick/git-projects/arquigames-cubes/node_modules/vue-sweetalert2/dist/index.d.ts
3:18 Could not find a declaration file for module 'sweetalert2/dist/sweetalert2.min.js'. '/home/erick/git-projects/arquigames-cubes/node_modules/sweetalert2/dist/sweetalert2.min.js' implicitly has an 'any' type.
  Try `npm install @types/sweetalert2` if it exists or add a new declaration (.d.ts) file containing `declare module 'sweetalert2/dist/sweetalert2.min.js';`
    1 | import Vue from 'vue';
    2 | import { SweetAlertOptions } from 'sweetalert2';
  > 3 | import Swal from 'sweetalert2/dist/sweetalert2.min.js';
      |                  ^
    4 | declare type VueSwalInstance = typeof Swal.fire;
    5 | declare module 'vue/types/vue' {
    6 |     interface Vue {
Version: typescript 3.5.2
Time: 5688ms

**Comment by avil13** [comment]
Fixed in `v2.1.1`
