### ISSUE TITLE
Ghost version 2.1.1 on npm

### ISSUE THREAD

**Issue by AssetKid** [avil13/vue-sweetalert2#62]
Hey,

I have been using vue-sweetalert2 for quite sometime now. Before I update all my dependencies, I always do my due diligence to check what has changed in the new version.

I just got an alert for `vue-sweetalert2 2.1.1`. Naturally, I came here to check what has changed but the last commit was 5 days ago for `2.1.0`.

This is obviously a red flag for me. I did check the code a bit and noticed a few changes in the  `dist` folder (Nothing malicious)

Where did 2.1.1 come from? What was added/removed/changed?

I did notice the file size decreased slightly in 2.1.1.

**Comment by avil13** [comment]
My mistake. Forgot to push the changes from `dev` branch.

https://github.com/avil13/vue-sweetalert2/blob/master/CHANGELOG.md
