### ISSUE TITLE
Sweetalert in IE 10

### ISSUE THREAD

**Issue by makoneth** [avil13/vue-sweetalert2#70]
I am using Sweetalert2 and it works perfectly in Chrome, Edge, IE 11 but IE 10. The problem is that when I try to open the pop-up window, it hides the pop-up window but also freezes everything! The screen user will not be able to click anywhere the page!

**Comment by vincentdh** [comment]
Hi,

The Sweetalert2 library does not support IE10.  Please refer to https://github.com/sweetalert2/sweetalert2#browser-compatibility

Thanks.
