### ISSUE TITLE
Toast and position are unknown parameters

### ISSUE THREAD

**Issue by RadiatedMonkey** [avil13/vue-sweetalert2#75]

**Comment by avil13** [comment]
In case of detection of a bug, please attach a link to https://codesandbox.io/ because reproducing your environment is very difficult.

**Comment by vincentdh** [comment]
@RadiatedMonkey Here is a working example on [codesandbox.io](https://codesandbox.io/embed/vue-sweetalert2-issue-75-demo-lr688)
Feel free to fork this sandbox and reproduce your error.

**Comment by solamichealolawale** [comment]
SweetAlert2: Unknown parameter "icon"

I try using the above sandbox url by replacing the text to 

`{
                    icon: 'success',
                    title: 'Signed in successfully'
                }`;

**Comment by vincentdh** [comment]
@solamichealolawale The current version (2.1.5) of vue-sweetalert2 is based on sweetalert2 8.x in which is using the parameter type instead of icon.  The icon parameter have been introduced in the version 9.x of sweetalert2.

**Comment by carlos-mora** [comment]
what a pain! Even in 8.x documentation, the sample shows 'icon' instead of 'type'. I've been looking around for a clue on this issue.

**Comment by doubleprincez** [comment]
Ain't this a b**ch!!!! What has "type" done to you!!!!! Aaaaaaaah!!!!!

**Comment by avil13** [comment]
Regarding the position, the item in the documentation.
https://sweetalert2.github.io/#position

Otherwise, it looks like the problem is no longer relevant
