### ISSUE TITLE
SweetAlert dialog appearing at the bottom of screen - No CSS

### ISSUE THREAD

**Issue by mgd216** [avil13/vue-sweetalert2#80]
- Version: 2.1.4
  - Platform: Windows

Following this message in the SweetAlert GitHub regarding importing SweetAlert:

https://github.com/sweetalert2/sweetalert2/issues/659

I updated src/index.ts line 4 FROM:

import Swal from 'sweetalert2/dist/sweetalert2.js';

TO:

import Swal from 'sweetalert2/dist/sweetalert2.all.js';

This fixed the issue of the dialog appears at the bottom of the screen, most likely because the CSS was not induced with just sweetalert2.js.

**Comment by vincentdh** [comment]
Hi @mgd216 

The file sweetalert2.js is the right file to import in the index.ts.  This file does not contain the CSS which allows the custom style.

If you want to use the default style, after your import for VueSweetAlert2, you need to import the CSS.

```js
// main.js
import Vue from 'vue';
import VueSweetalert2 from 'vue-sweetalert2';

// Do not import this file if you want to use custom style
import 'sweetalert2/dist/sweetalert2.min.css';

Vue.use(VueSweetalert2);
```

You can refer to the [README](https://github.com/avil13/vue-sweetalert2/blob/master/README.md) for more information.

Thanks

**Comment by mgd216** [comment]
Yup, RTRF (Read the Readme First ;) )  Thanks , inlcuding the css in my import worked.

**Comment by sukhveersingh0779** [comment]
Thankyou so much. My issue is fixed with this
