### ISSUE TITLE
Trying to use the black theme

### ISSUE THREAD

**Issue by croftman** [avil13/vue-sweetalert2#83]
Hey !

I install the sweetalert2 black theme and import it in the css, but I see with this plugin the css is in "inline" and I can see the black css in the "_core.scss"

I import sweet alert like the doc :

```javascript
import VueSweetalert2 from 'vue-sweetalert2';
const options = {
    showCloseButton: true,
    confirmButtonText: 'Envoyer',
    cancelButtonText: 'Annuler',
    showCancelButton: true,
    showLoaderOnConfirm: true,
    inputAttributes: {
        autocapitalize: 'off'
    },
};
Vue.use(VueSweetalert2, options);
```

And the css in the app.scss

```scss
@import '~@sweetalert2/themes/dark/dark.scss';
```

How can I import the theme ?

Thank you !

  - Version: 2.1.4
  - Platform: Debian

**Comment by avil13** [comment]
Hi.
Maybe this is because sweetalert2 has no dark theme? 
I did not find it in the package.

![image](https://user-images.githubusercontent.com/1606172/67983892-ad73ed00-fc36-11e9-9295-68140c83a500.png)

**Comment by avil13** [comment]
![image](https://user-images.githubusercontent.com/1606172/67984078-1196b100-fc37-11e9-9f88-02f70a29db37.png)

**Comment by croftman** [comment]
Here for the theme : https://github.com/sweetalert2/sweetalert2-themes

**Comment by avil13** [comment]
https://github.com/avil13/vue-sweetalert2-example/blob/master/src/components/BlackAlert.vue

Watch this example.

**Comment by yogithesymbian** [comment]
> Here for the theme : https://github.com/sweetalert2/sweetalert2-themes

thanks its work i just put these code on my code  for example **Table.vue**

```
<style lang="scss">
  @import '@core/scss/vue/libs/vue-sweetalert.scss'; // to work with dark mode / light mode
</style>
```

so the theme follow my mode is dark or light mode would like automatically changes, by the way i use template from marketplace but the documentation is not helpfully.
