### ISSUE TITLE
TypeError: this.constructor.argsToParams is not a function when calling "this.$swal.fire()"

### ISSUE THREAD

**Issue by rhnchn9** [avil13/vue-sweetalert2#84]
version: 2.1.4
platform: Mac

I am getting following error message in the console when I am using "this.$swal.fire()":

TypeError: this.constructor.argsToParams is not a function

In earlier version(1.6.4), this used to be working fine before but not now anymore once I updated to the latest version (which is 2.1.4 now).So, I reverted back to the older version.

You can check this in CodeSandbox below:
https://codesandbox.io/s/vue-template-hqsly?fontsize=14

Just click the button "show alert".

Side note: I tried replacing "this.$swal.fire()" to "this.$swal()" and it worked as before but then I have to make changes everywhere in my code.

Please let me know if this can be fixed or I have to assume it's a breaking change.

**Comment by Sephster** [comment]
Seconded. I am getting this as well (on the same version)

**Comment by avil13** [comment]
fixed in version 2.1.5.

Tnx for issue.

**Comment by rhnchn9** [comment]
thnx for the fix :)

**Comment by cwahome** [comment]
Upgrading the version to 2.1.5 and changing from using `this.$swal()` to `this.$swal.fire()` worked for me
