### ISSUE TITLE
Suggestion: Create a vue-sweetalert2 version 3.x to update to sweetalert 9.x

### ISSUE THREAD

**Issue by vincentdh** [avil13/vue-sweetalert2#86]
Some [breaking changes](https://github.com/sweetalert2/sweetalert2/releases/tag/v9.0.0) have been introduced in v9.x of sweetalert2.

I suggest to create a v3.x of vue-sweetalert2 to update the dependency and not breaking projects that are using version 2.x of vue-sweetalert2.

**Comment by vincentdh** [comment]
This issue is related to issue #75 and can close it

**Comment by hitostacha** [comment]
Would be nicer if you were able to pass an instance of Sweetalert in case you want to use newer versions of swal.
Something like:
`
import swal from 'sweetalert2';
import VueSweetAlert2 from 'vue-sweetalert2';
import Vue from 'vue';

Vue.use(VueSweetAlert2, swal)
`

**Comment by avil13** [comment]
This library is just a wrapper for easy use.
She always uses the latest major version.
V3 just upgraded sweetalert2 to version 9.

Your option negates the meaning of using this library.
It will be easier to use sweetalert2 directly, simply adding the library to the components themselves.

But thanks for the idea, maybe I just haven’t understood all its advantages.
