### ISSUE TITLE
Animations  popup enter and leave not work

### ISSUE THREAD

**Issue by HacheB** [avil13/vue-sweetalert2#87]
Animation for enter and leave aren't working.
Animated.css is OK, he works good on other components.

I use `"vue-sweetalert2": "^2.1.5"` with webpack on mac (High sierra).
I try to use this (https://sweetalert2.github.io/#show-class): 
```
showClass: {
    popup: 'animated fadeInDown faster'
  },
  hideClass: {
    popup: 'animated fadeOutUp faster'
  }
```

## 👋 Good day

- If you've found a bug, please attach a link to a sandbox from [codesandbox.io](https://codesandbox.io/) that reproduce your bug.  Without the sandbox, it can be verry difficult to recreate your environment and fix the bug.

## I also want to know

  - Version:
  - Platform:
  - Subsystem:

**Comment by vincentdh** [comment]
Hi,

showClass and hideClass are part of SweetAlert2 **v9.x** and vue-sweetalert2 **v2.1.5** is based on SweetAlert2 **v8.x**.

A suggestion to update the dependency have been made in #86 

Thanks.

**Comment by HacheB** [comment]
Thanks for the answer.
