### ISSUE TITLE
Question: More than two buttons

### ISSUE THREAD

**Issue by BernhardSchlegel** [avil13/vue-sweetalert2#88]
Does somebody know a "vueish" way to create more than 2 buttons with this (great) lib, or shall I do the JQuery method as proposed [here](https://stackoverflow.com/a/39269229/1701600).

**Comment by avil13** [comment]
Hello. Can be to know, what is worth task at all? What do you expect? This is the library for displaying the alert. You at all can not use vue-sweatalert2 and write all on vanilla.
