### ISSUE TITLE
Modify the height of body to automatic

### ISSUE THREAD

**Issue by Nemutagk** [avil13/vue-sweetalert2#91]
good day

The bug I present is that it modifies the height of the body to automatic, in a common site it will not present a problem, but in places that the body with the 100% high is required it presents an error since when deploying the modal sweetalert modifies the height to automatic, so the content is unchecked, disabling this option does not harm the modal at all, so I think that you should not make such a change because it is not necessary, or at least not include the "!important" sentence.

Test code:
[https://codesandbox.io/s/eager-https-f4wmd?fontsize=14&hidenavigation=1&theme=dark](url)

Version vue-sweetalert2: 3.0.1
Vue version: 2.6.10

**Comment by avil13** [comment]
Good afternoon.
Thank you for a good example.

I have a couple of comments.

vue-sweetalert2 is just a wrapper that helps Vue applications conveniently use the sweetalert2 library.
Therefore, at most, it is possible to make PR in the main library.

In General, your case looks so private that I think it is easier to solve it using CSS styles.

```CSS
body.swal2-height-auto {
    height: inherit !important; /* the value you need */
}
```

**Comment by Nemutagk** [comment]
Thank you very much for answering!

I am very sorry to see published here, I had doubts whether to place it here or in the original repository of sweetalert2, I opted for using VueJS.

Regarding your recommendation is precisely what you do, however, as you say, it is a very particular error, I do not know if it is worth publishing it in the original repository.

Thanks again for your reply.
