### ISSUE TITLE
heightAuto not working on mixin

### ISSUE THREAD

**Issue by caiquecastro** [avil13/vue-sweetalert2#92]
Defining heightAuto on global setup is not working.

Vue.use(VueSweetalert2, {
  heightAuto: false
});

It only works on direct on fire method:

this.$swal.fire({
        text: "Teste",
        //heightAuto: false,
});

https://codesandbox.io/s/cool-cdn-3h5fr

## I also want to know

  - Version: latest
  - Platform: windows and linux
  - Subsystem: No

**Comment by avil13** [comment]
Sorry I couldn’t answer for a long time.
Try updating.
