### ISSUE TITLE
sweet alert modal cant render css

### ISSUE THREAD

**Issue by mnce92** [avil13/vue-sweetalert2#94]
The normal function works fine, however I notice that the styling not working, css class not rendering thus the modal is right at the bottom with simplest form of html

  - Version: 3.0.1
  - Platform: vue-cli/ nodejs
  - Subsystem:

![image](https://user-images.githubusercontent.com/36837235/74703507-570fd600-5248-11ea-8b9e-e6843c3d2634.png)

**Comment by avil13** [comment]
Hi. 
I find it difficult to understand what actually happens without code. Perhaps you did not include CSS at all. Or your styles are in style scope tag?

**Comment by andrewrusselrenner** [comment]
Same happened to me with Nuxtjs. I add a simple call like this in my methods:

`...
methods: {
    tesmodal() {
      this.$swal("okokok");
    }
  }
...`

and a bootstrap button: 
`<b-button type="submit" variant="primary" @click.prevent="tesmodal">Klik gue sekarang</b-button>`

and this happened:
![image](https://user-images.githubusercontent.com/5303871/83058098-69d94880-a08a-11ea-81cb-a9ef1bff0292.png)

**Comment by KumariShalini** [comment]
> Same happened to me with Nuxtjs. I add a simple call like this in my methods:
> 
> `... methods: { tesmodal() { this.$swal("okokok"); } } ...`
> 
> and a bootstrap button:
> `<b-button type="submit" variant="primary" @click.prevent="tesmodal">Klik gue sekarang</b-button>`
> 
> and this happened:
> ![image](https://user-images.githubusercontent.com/5303871/83058098-69d94880-a08a-11ea-81cb-a9ef1bff0292.png)
> 
> Edit:
> In the end I add this manually in my main.scss
> `@import "~sweetalert2/src/variables";`
> `@import "~sweetalert2/src/sweetalert2";`
> 
> and now it's working fine.
> ![image](https://user-images.githubusercontent.com/5303871/83058830-8e81f000-a08b-11ea-8e03-63ec98f0d62b.png)

How can i add it in nuxt ?, can you help me here? Thank you

**Comment by avil13** [comment]
@KumariShalini this can be done in the "layout/default.vue file"

**Comment by KumariShalini** [comment]
> @KumariShalini this can be done in the `layout/default.vue` file

okay, i tried it in default.vue in layout, it throws an error "Cannot find module '~sweetalert2/src/variables' "

**Comment by rhnchn9** [comment]
import 'sweetalert2/dist/sweetalert2.min.css'; inside script tag in layout/default.vue file worked for me.
