### ISSUE TITLE
Guithub releases/tags

### ISSUE THREAD

**Issue by joelpro2** [avil13/vue-sweetalert2#96]
hi,

This is not a bug but a pretty important improvement.
Your Repo doesn't have tags neither releases, and youre actually in version 3.0.3

I have version 2.1.5 and I dont know what has changed to 3.x version, if there are breaking changes, because you dont even have a release note.

It's pretty simple to make with github and help alot

Thanks.

**Comment by JorgenSolli** [comment]
I second this

**Comment by avil13** [comment]
Fixed here (415404b2f2)
