### ISSUE TITLE
Cannot disable css including in nuxt

### ISSUE THREAD

**Issue by Rekryt** [avil13/vue-sweetalert2#98]
Hello. Then we import vue-sweetalert2 importing of css styles is hardcoded in package sweetalert2.
At nuxt, with "extractCSS: true" option, css is not extracting and stay in <style> at <head> tag after extracted styles. As a result hardcoded default styles overwrite extracted styles, as example styles from @sweetalert2/theme-dark.

It would be convenient to have option for not include css.

I fixed it with this method - by rewriting the import...
from
`import Swal from 'sweetalert2';`
to
`import Swal from 'sweetalert2/dist/sweetalert2.min.js';`

but this is not the best way.

Have a nice day.

**Comment by avil13** [comment]
Hi. Thank you very much for the suggestion.
May I ask for a pull request?
I have absolutely no free time. But I don’t want to drop the project.
I would be grateful if the community helped me at least a little.

Anyway, thanks.

**Comment by Rekryt** [comment]
Ok https://github.com/avil13/vue-sweetalert2/pull/100
